import * as React from 'react';
import { actionCreators } from '../../store/SmartGoals';
import { connect } from 'react-redux';
import { ApplicationState } from '../../store/index';
import CardGroupCard from '../common/CardGroupCard';
import PrintButton from '../common/PrintButton';
import CancelButton from '../common/CancelButton';
import { RouteComponentProps } from 'react-router';


type PerformanceReportProps = {
    user: string
    results: any[];
} & typeof actionCreators
  & RouteComponentProps<{}>;

class PerformanceReport extends React.Component<PerformanceReportProps> {


    constructor(props: PerformanceReportProps) {
        super(props);
        this.print = this.print.bind(this);
    }
    public render() {

        const { results, user, history } = this.props;
        const today = new Date();
        const date = today.getFullYear() + '/' + (today.getMonth() + 1) + '/' + today.getDate();
        const time = today.getHours() + ':' + today.getMinutes() + ':' + today.getSeconds();
        const dateTime = date + ' ' + time;


        return <div className="m-4">
            <div className="row m-3" >
                <PrintButton id="printbtn" className="mr-2" onClick={this.print}/>
                {' '}
                <CancelButton id="printbtn" onClick={history.goBack}/>
            </div>
            <h3 className="text-center mt-3"> INDIVIDUAL PERFORMANCE REPORT </h3>

            <CardGroupCard heading={`${user.toUpperCase()} PERFORMANCE`} headingPosition="text-center" >

                <div className="row ml-1 mr-1 mt-3 justify-content-around">
                    <div>Assignments resolved({results[0].days} days) :{' '}{results[0].resolved} </div>
                    <div>Assignments resolved(per day) :{' '}{results[0].disposPerDay} </div>
                    <div>Assignments rejected({results[0].days} days) :{' '}{results[0].rejected} </div>

                </div>

                <div className="row ml-1 mr-1 mb-3 justify-content-around">
                    <div>Outstanding assignments :{' '}{results.map(item => item.outStandingDays).reduce((prev, next) => prev + next)} </div>
                </div>

            </CardGroupCard>

            <div className="row ml-1 mr-1 justify-content-between">
                <div>Report generated by :{user} </div>
                <div>Report generated on :{dateTime} </div>
            </div>

        </div>;

    }

    private print() {
        window.print();
    }
}

export default connect(
    (state: ApplicationState) => {
        return {
            results: state.smartGoals.performanceInfo,
            user: state.smartGoals.criteria.user
        };
    },
    actionCreators
)(PerformanceReport);
